framework:
  secret: '%env(APP_SECRET)%'
  default_locale: pl
  #csrf_protection: ~
  #http_method_override: true

  # uncomment this entire section to enable sessions
  session:
    handler_id: ~

  #esi: ~
  #fragments: ~
  php_errors:
    log: true
  router:
    strict_requirements: ~

  assets:
    json_manifest_path: '%kernel.project_dir%/public/build/dev/manifest.json'